uploads = []
generated = []

[[outputs]]
id = "SVjpprpGJjo8YMg_Xo_9R"
uri = "file://sairolotech-build.tar.gz"
type = "unspecified"
title = "SAI Rolotech CRM - Production Build"

[[outputs]]
id = "DSB9sThxsxlB95oSXPkDf"
uri = "file://android-release-aab.zip"
type = "unspecified"
title = "SAI RoloTech CRM — Android AAB (Play Store Upload File)"

[[outputs]]
id = "wXnWHMtWApSJGNLkpSF2L"
uri = "file://android-api35-release.zip"
type = "unspecified"
title = "SAI RoloTech CRM — Android AAB (API Level 35) — Play Store Ready"

[[outputs]]
id = "BnfWSqOS_wJesX1EqShi1"
uri = "file://android-v2-release.zip"
type = "unspecified"
title = "SAI RoloTech CRM — Android AAB v2 (API 35, VersionCode 3)"

[[outputs]]
id = "BbBNN00PZtAVMWwvlnBhO"
uri = "file://public/android-v4-release.zip"
type = "unspecified"
title = "android-v4-release.zip (versionCode=4)"

[[outputs]]
id = "xk39Lk3GBQXCooTZY0sxJ"
uri = "file://public/android-versionCode4-FINAL.zip"
type = "unspecified"
title = "android-versionCode4-FINAL.zip — Play Store ke liye Upload Karo"
